# configs/default.yaml
seed:          42
device:       cuda
data:
  batch_size:  16
  num_workers: 0
  patch_size: 256
  data_dir:    ./data/preprocessed
model:
  base_channels: 32
  depth:         4
  batch_norm: true
train:
  epochs:       100
  weight_decay: 1e-5
optimizer:
  type:         Adam
  lr:           1e-3
  betas:        [0.9, 0.999]
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false