# configs/default.yaml
seed:          42
device:       cuda
data:
  batch_size:  64
  num_workers: 48
  patch_size: 256
  patches_per_image: 64
  data_dir:    
model:
  base_channels: 32
  depth:         4
  batch_norm: true
train:
  epochs:       100
  weight_decay: 3e-5
optimizer:
  type:         Adam
  lr:           1e-4
  betas:        [0.9, 0.999]
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
  hydra_logging:
    handlers: []
  job_logging:
    handlers: []